### ISSUE TITLE
docker system prune 使わないの？

### ISSUE THREAD

**Issue by gaogao-9** [mpyw/docker-clean#1]
https://docs.docker.com/engine/reference/commandline/system_prune/

**Comment by mpyw** [comment]
あっフィルターこっちでも使えるのか

**Comment by gaogao-9** [comment]
ところでランダム名だけ消したい理由もあんまりわかんないけど、思考停止で `docker system prune -a -f --volumes` じゃだめなんですか

**Comment by mpyw** [comment]
DBのシーディングとか、プロビジョニング的な処理やってるやつは起動が重いので `stop` 状態で残しておきたい
ランダム名のやつはビルドエラー等で勝手に溜まったゴミという想定

**Comment by gaogao-9** [comment]
なるほどねって感じだ。僕だったらstatusだけでゆるくfilterするか、あるいはそもそもdb起動中に実行して掃除するやつだ…
